engines:
  # ... CONFIG CONTENT ...
  phpmd:
    enabled: true
    # ... SHOW ONLY FATAL ERRORS, HIDE WARNINGS ...
    checks:
      Design/TooManyPublicMethods:
        enabled: false
      Design/TooManyMethods:
        enabled: false
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      UnusedFormalParameter:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      ExcessivePublicCount:
        enabled: false
      Design/LongClass:
        enabled: false
# ... CONFIG CONTENT ...