engines:
  # ... CONFIG CONTENT ...
  phpmd:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Design/TooManyPublicMethods:
        enabled: false
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      UnusedFormalParameter:
        enabled: false
# ... CONFIG CONTENT ...